language: php
sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

install:
  # Remove Xdebug.
  - phpenv config-rm xdebug.ini || true
  # Install Composer.
  - composer install

script:
  # Run PHPUnit tests.
  - ./vendor/bin/phpunit -c ./phpunit.xml --coverage-text --strict
